export const FETCH_LIST_CANDIDATE_ORDER_REQUEST = "FETCH_LIST_CANDIDATE_ORDER_REQUEST";
export const FETCH_LIST_CANDIDATE_ORDER_SUCCESS = "FETCH_LIST_CANDIDATE_ORDER_SUCCESS";
export const FETCH_LIST_CANDIDATE_ORDER_ERROR = "FETCH_LIST_CANDIDATE_ORDER_ERROR";

export const FETCH_LIST_CANDIDATE_REQUEST = "FETCH_LIST_CANDIDATE_REQUEST";
export const FETCH_LIST_CANDIDATE_SUCCESS = "FETCH_LIST_CANDIDATE_SUCCESS";
export const FETCH_LIST_CANDIDATE_ERROR = "FETCH_LIST_CANDIDATE_ERROR";

export const FETCH_LIST_CANDIDATE_ADMIN_REQUEST = "FETCH_LIST_CANDIDATE_ADMIN_REQUEST";
export const FETCH_LIST_CANDIDATE_ADMIN_SUCCESS = "FETCH_LIST_CANDIDATE_ADMIN_SUCCESS";
export const FETCH_LIST_CANDIDATE_ADMIN_ERROR = "FETCH_LIST_CANDIDATE_ADMIN_ERROR";

export const CHANGE_ACTIVE_REQUEST = "CHANGE_ACTIVE_REQUEST";
export const CHANGE_ACTIVE_SUCCESS = "CHANGE_ACTIVE_SUCCESS";
export const CHANGE_ACTIVE_ERROR = "CHANGE_ACTIVE_ERROR";

export const CHANGE_ORDER_REQUEST = "CHANGE_ORDER_REQUEST";
export const CHANGE_ORDER_SUCCESS = "CHANGE_ORDER_SUCCESS";
export const CHANGE_ORDER_ERROR = "CHANGE_ORDER_ERROR";

export const FETCH_INFO_CANDIDATE_REQUEST = "FETCH_INFO_CANDIDATE_REQUEST";
export const FETCH_INFO_CANDIDATE_SUCCESS = "FETCH_INFO_CANDIDATE_SUCCESS";
export const FETCH_INFO_CANDIDATE_ERROR = "FETCH_INFO_CANDIDATE_ERROR";

export const UPDATE_INFO_CANDIDATE_REQUEST = "UPDATE_INFO_CANDIDATE_REQUEST";
export const UPDATE_INFO_CANDIDATE_SUCCESS = "UPDATE_INFO_CANDIDATE_SUCCESS";
export const UPDATE_INFO_CANDIDATE_ERROR = "UPDATE_INFO_CANDIDATE_ERROR";

export const FETCH_LIST_RECRUITMENT_APPLY_REQUEST = "FETCH_LIST_RECRUITMENT_APPLY_REQUEST";
export const FETCH_LIST_RECRUITMENT_APPLY_SUCCESS = "FETCH_LIST_RECRUITMENT_APPLY_SUCCESS";
export const FETCH_LIST_RECRUITMENT_APPLY_ERROR = "FETCH_LIST_RECRUITMENT_APPLY_ERROR";

export const GETDETAIL_CANDIDATE_REQUEST = "GETDETAIL_CANDIDATE_REQUEST";
export const GETDETAIL_CANDIDATE_SUCCESS = "GETDETAIL_CANDIDATE_SUCCESS";
export const GETDETAIL_CANDIDATE_ERROR = "GETDETAIL_CANDIDATE_ERROR";

export const DELETE_APPLY_JOB_REQUEST = "DELETE_APPLY_JOB_REQUEST";
export const DELETE_APPLY_JOB_SUCCESS = "DELETE_APPLY_JOB_SUCCESS";
export const DELETE_APPLY_JOB_ERROR = "DELETE_APPLY_JOB_ERROR";

export const DASHBOARD_CANDIDATE_REQUEST = "DASHBOARD_CANDIDATE_REQUEST";
export const DASHBOARD_CANDIDATE_SUCCESS = "DASHBOARD_CANDIDATE_SUCCESS";
export const DASHBOARD_CANDIDATE_ERROR = "DASHBOARD_CANDIDATE_ERROR";