export const FETCH_LIST_CAREER_REQUEST = "FETCH_LIST_CAREER_REQUEST";
export const FETCH_LIST_CAREER_SUCCESS = "FETCH_LIST_CAREER_SUCCESS";
export const FETCH_LIST_CAREER_ERROR = "FETCH_LIST_CAREER_ERROR";