export const ADD_CV_REQUEST = "ADD_CV_REQUEST";
export const ADD_CV_SUCCESS = "ADD_CV_SUCCESS";
export const ADD_CV_ERROR = "ADD_CV_ERROR";

export const GETCV_BY_USERID_REQUEST = "GETCV_BY_USERID_REQUEST";
export const GETCV_BY_USERID_SUCCESS = "GETCV_BY_USERID_SUCCESS";
export const GETCV_BY_USERID_ERROR = "GETCV_BY_USERID_ERROR";

export const GETCV_BY_CANDIDATEID_REQUEST = "GETCV_BY_CANDIDATEID_REQUEST";
export const GETCV_BY_CANDIDATEID_SUCCESS = "GETCV_BY_CANDIDATEID_SUCCESS";
export const GETCV_BY_CANDIDATEID_ERROR = "GETCV_BY_CANDIDATEID_ERROR";

export const GETCV_BY_ID_REQUEST = "GETCV_BY_ID_REQUEST";
export const GETCV_BY_ID_SUCCESS = "GETCV_BY_ID_SUCCESS";
export const GETCV_BY_ID_ERROR = "GETCV_BY_ID_ERROR";

export const GET_DATA_USER_SUCCESS = "GET_DATA_USER_SUCCESS";
export const GET_DATA_CV_SUCCESS = "GET_DATA_CV_SUCCESS";

export const UPDATE_CV_REQUEST = "UPDATE_CV_REQUEST";
export const UPDATE_CV_SUCCESS = "UPDATE_CV_SUCCESS";
export const UPDATE_CV_ERROR = "UPDATE_CV_ERROR";

export const DELETE_CV_REQUEST = "DELETE_CV_REQUEST";
export const DELETE_CV_SUCCESS = "DELETE_CV_SUCCESS";
export const DELETE_CV_ERROR = "DELETE_CV_ERROR";