export const FETCH_LIST_EMPLOYER_ORDER_REQUEST = "FETCH_LIST_EMPLOYER_ORDER_REQUEST";
export const FETCH_LIST_EMPLOYER_ORDER_SUCCESS = "FETCH_LIST_EMPLOYER_ORDER_SUCCESS";
export const FETCH_LIST_EMPLOYER_ORDER_ERROR = "FETCH_LIST_EMPLOYER_ORDER_ERROR";

export const FETCH_LIST_EMPLOYER_REQUEST = "FETCH_LIST_EMPLOYER_REQUEST";
export const FETCH_LIST_EMPLOYER_SUCCESS = "FETCH_LIST_EMPLOYER_SUCCESS";
export const FETCH_LIST_EMPLOYER_ERROR = "FETCH_LIST_EMPLOYER_ERROR";

export const FETCH_INFO_EMPLOYER_REQUEST = "FETCH_INFO_EMPLOYER_REQUEST";
export const FETCH_INFO_EMPLOYER_SUCCESS = "FETCH_INFO_EMPLOYER_SUCCESS";
export const FETCH_INFO_EMPLOYER_ERROR = "FETCH_INFO_EMPLOYER_ERROR";

export const UPDATE_INFO_EMPLOYER_REQUEST = "UPDATE_INFO_EMPLOYER_REQUEST";
export const UPDATE_INFO_EMPLOYER_SUCCESS = "UPDATE_INFO_EMPLOYER_SUCCESS";
export const UPDATE_INFO_EMPLOYER_ERROR = "UPDATE_INFO_EMPLOYER_ERROR";

export const FETCH_LIST_EMPLOYER_ADMIN_REQUEST = "FETCH_LIST_EMPLOYER_ADMIN_REQUEST";
export const FETCH_LIST_EMPLOYER_ADMIN_SUCCESS = "FETCH_LIST_EMPLOYER_ADMIN_SUCCESS";
export const FETCH_LIST_EMPLOYER_ADMIN_ERROR = "FETCH_LIST_EMPLOYER_ADMIN_ERROR";

export const CHANGE_ACTIVE_REQUEST = "CHANGE_ACTIVE_REQUEST";
export const CHANGE_ACTIVE_SUCCESS = "CHANGE_ACTIVE_SUCCESS";
export const CHANGE_ACTIVE_ERROR = "CHANGE_ACTIVE_ERROR";

export const CHANGE_ORDER_REQUEST = "CHANGE_ORDER_REQUEST";
export const CHANGE_ORDER_SUCCESS = "CHANGE_ORDER_SUCCESS";
export const CHANGE_ORDER_ERROR = "CHANGE_ORDER_ERROR";

export const DASHBOARD_EMPLOYER_REQUEST = "DASHBOARD_EMPLOYER_REQUEST";
export const DASHBOARD_EMPLOYER_SUCCESS = "DASHBOARD_EMPLOYER_SUCCESS";
export const DASHBOARD_EMPLOYER_ERROR = "DASHBOARD_EMPLOYER_ERROR";

export const DELETE_RECRUITMENT_REQUEST = "DELETE_RECRUITMENT_REQUEST";
export const DELETE_RECRUITMENT_SUCCESS = "DELETE_RECRUITMENT_SUCCESS";
export const DELETE_RECRUITMENT_ERROR = "DELETE_RECRUITMENT_ERROR";

export const GETDETAIL_EMPLOYER_REQUEST = "GETDETAIL_EMPLOYER_REQUEST";
export const GETDETAIL_EMPLOYER_SUCCESS = "GETDETAIL_EMPLOYER_SUCCESS";
export const GETDETAIL_EMPLOYER_ERROR = "GETDETAIL_EMPLOYER_ERROR";

export const GET_RECRUITMENTS_BY_EMPLOYER_ID_REQUEST = "GET_RECRUITMENTS_BY_EMPLOYER_ID_REQUEST";
export const GET_RECRUITMENTS_BY_EMPLOYER_ID_SUCCESS = "GET_RECRUITMENTS_BY_EMPLOYER_ID_SUCCESS";
export const GET_RECRUITMENTS_BY_EMPLOYER_ID_ERROR = "GET_RECRUITMENTS_BY_EMPLOYER_ID_ERROR";

export const DELETE_APPLY_JOB_REQUEST = "DELETE_APPLY_JOB_REQUEST";
export const DELETE_APPLY_JOB_SUCCESS = "DELETE_APPLY_JOB_SUCCESS";
export const DELETE_APPLY_JOB_ERROR = "DELETE_APPLY_JOB_ERROR";