export const FETCH_LIST_RECRUITMENT_ORDER_REQUEST = "FETCH_LIST_RECRUITMENT_ORDER_REQUEST";
export const FETCH_LIST_RECRUITMENT_ORDER_SUCCESS = "FETCH_LIST_RECRUITMENT_ORDER_SUCCESS";
export const FETCH_LIST_RECRUITMENT_ORDER_ERROR = "FETCH_LIST_RECRUITMENT_ORDER_ERROR";

export const FETCH_LIST_RECRUITMENT_REQUEST = "FETCH_LIST_RECRUITMENT_REQUEST";
export const FETCH_LIST_RECRUITMENT_SUCCESS = "FETCH_LIST_RECRUITMENT_SUCCESS";
export const FETCH_LIST_RECRUITMENT_ERROR = "FETCH_LIST_RECRUITMENT_ERROR";

export const FETCH_LIST_RECRUITMENT_BY_USERID_REQUEST = "FETCH_LIST_RECRUITMENT_BY_USERID_REQUEST";
export const FETCH_LIST_RECRUITMENT_BY_USERID_SUCCESS = "FETCH_LIST_RECRUITMENT_BY_USERID_SUCCESS";
export const FETCH_LIST_RECRUITMENT_BY_USERID_ERROR = "FETCH_LIST_RECRUITMENT_BY_USERID_ERROR";

export const FETCH_LIST_CANDIDATE_BY_USERID_REQUEST = "FETCH_LIST_CANDIDATE_BY_USERID_REQUEST";
export const FETCH_LIST_CANDIDATE_BY_USERID_SUCCESS = "FETCH_LIST_CANDIDATE_BY_USERID_SUCCESS";
export const FETCH_LIST_CANDIDATE_BY_USERID_ERROR = "FETCH_LIST_CANDIDATE_BY_USERID_ERROR";

export const FETCH_LIST_CV_BY_USERID_REQUEST = "FETCH_LIST_CV_BY_USERID_REQUEST";
export const FETCH_LIST_CV_BY_USERID_SUCCESS = "FETCH_LIST_CV_BY_USERID_SUCCESS";
export const FETCH_LIST_CV_BY_USERID_ERROR = "FETCH_LIST_CV_BY_USERID_ERROR";

export const ADD_RECRUITMENT_REQUEST = "ADD_RECRUITMENT_REQUEST";
export const ADD_RECRUITMENT_SUCCESS = "ADD_RECRUITMENT_SUCCESS";
export const ADD_RECRUITMENT_ERROR = "ADD_RECRUITMENT_ERROR";

export const GETINFO_EDIT_RECRUITMENT_REQUEST = "GETINFO_EDIT_RECRUITMENT_REQUEST";
export const GETINFO_EDIT_RECRUITMENT_SUCCESS = "GETINFO_EDIT_RECRUITMENT_SUCCESS";
export const GETINFO_EDIT_RECRUITMENT_ERROR = "GETINFO_EDIT_RECRUITMENT_ERROR";

export const UPDATE_RECRUITMENT_REQUEST = "UPDATE_RECRUITMENT_REQUEST";
export const UPDATE_RECRUITMENT_SUCCESS = "UPDATE_RECRUITMENT_SUCCESS";
export const UPDATE_RECRUITMENT_ERROR = "UPDATE_RECRUITMENT_ERROR";

export const FETCH_LIST_RECRUITMENT_ADMIN_REQUEST = "FETCH_LIST_RECRUITMENT_ADMIN_REQUEST";
export const FETCH_LIST_RECRUITMENT_ADMIN_SUCCESS = "FETCH_LIST_RECRUITMENT_ADMIN_SUCCESS";
export const FETCH_LIST_RECRUITMENT_ADMIN_ERROR = "FETCH_LIST_RECRUITMENT_ADMIN_ERROR";

export const CHANGE_ACTIVE_REQUEST = "CHANGE_ACTIVE_REQUEST";
export const CHANGE_ACTIVE_SUCCESS = "CHANGE_ACTIVE_SUCCESS";
export const CHANGE_ACTIVE_ERROR = "CHANGE_ACTIVE_ERROR";

export const CHANGE_ORDER_REQUEST = "CHANGE_ORDER_REQUEST";
export const CHANGE_ORDER_SUCCESS = "CHANGE_ORDER_SUCCESS";
export const CHANGE_ORDER_ERROR = "CHANGE_ORDER_ERROR";

export const GETDETAIL_RECRUITMENT_REQUEST = "GETDETAIL_RECRUITMENT_REQUEST";
export const GETDETAIL_RECRUITMENT_SUCCESS = "GETDETAIL_RECRUITMENT_SUCCESS";
export const GETDETAIL_RECRUITMENT_ERROR = "GETDETAIL_RECRUITMENT_ERROR";

export const DASHBOARD_CLIENT_REQUEST = "DASHBOARD_CLIENT_REQUEST";
export const DASHBOARD_CLIENT_SUCCESS = "DASHBOARD_CLIENT_SUCCESS";
export const DASHBOARD_CLIENT_ERROR = "DASHBOARD_CLIENT_ERROR";

export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_ERROR = "APPLY_JOB_ERROR";

export const DASHBOARD_ADMIN_REQUEST = "DASHBOARD_ADMIN_REQUEST";
export const DASHBOARD_ADMIN_SUCCESS = "DASHBOARD_ADMIN_SUCCESS";
export const DASHBOARD_ADMIN_ERROR = "DASHBOARD_ADMIN_ERROR";


