export const FETCH_LIST_SALARY_REQUEST = "FETCH_LIST_SALARY_REQUEST";
export const FETCH_LIST_SALARY_SUCCESS = "FETCH_LIST_SALARY_SUCCESS";
export const FETCH_LIST_SALARY_ERROR = "FETCH_LIST_SALARY_ERROR";