export const FETCH_LIST_TYPEOFWORK_REQUEST = "FETCH_LIST_TYPEOFWORK_REQUEST";
export const FETCH_LIST_TYPEOFWORK_SUCCESS = "FETCH_LIST_TYPEOFWORK_SUCCESS";
export const FETCH_LIST_TYPEOFWORK_ERROR = "FETCH_LIST_TYPEOFWORK_ERROR";